### ISSUE TITLE
non-stop loading spinning wheel after clicking a product Attribute Set

### ISSUE THREAD

**Issue by Eric0329** [MRLIVING/magento#17]
![image](https://user-images.githubusercontent.com/3777869/123212938-01ac9e80-d4f8-11eb-9ef0-19a14478f6ce.png)

### var/log/exception.log
[2021-06-23 07:28:29] main.CRITICAL: The "gallery_schedule_block0" block threw an exception, and it can't be rendered. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): The \"gallery_schedule_block0\" block threw an exception, and it can't be rendered. at /var/www/html/magento2/vendor/magento/framework/View/Element/ExceptionHandlerBlock.php:46)"} []

**Comment by uflins** [comment]
Amasty_AdminActionsLog ver 2.0.0 has bug of make the element ID twice defined in layout. Disable this extension can pass the problem, but not solved. 

**/var/www/html/magento2/var/log/system.log**

`/var/www/html/magento2/var/log/system.log:120272:[2021-06-24 05:05:00] main.CRITICAL: An element with a "gallery_schedule_block0.uploader" ID already exists. [] []`

**Comment by uflins** [comment]
Downgrade the version of Amasty_AdminActionsLog to ver1.2.13. 

Step1. Remove the latest version 2.0.0 . 

`composer remove amasty/adminactionslog ` 

Step2. ` composer require amasty/adminactionslog 1.2.13` 

Step3. CP tables(amasty_audit_active、amasty_audit_log、amasty_audit_login_attempts、amasty_audit_log_details、
amasty_audit_visit、 amasty_audit_visit_details) from old DB to m2prod's DB.
` ` ` 
-- --------------------------------------------------------
--Amasty_AdminActionsLog ver1.2.13.
--
-- 資料表結構 `amasty_audit_active`
--

CREATE TABLE `amasty_audit_active` (
  `id` int(10) UNSIGNED NOT NULL COMMENT 'Id',
  `session_id` text COMMENT 'Session Id',
  `recent_activity` datetime DEFAULT NULL COMMENT 'Recent Activity',
  `username` text COMMENT 'Username',
  `date_time` datetime DEFAULT NULL COMMENT 'Date Time',
  `name` text COMMENT 'Name',
  `ip` text COMMENT 'IP',
  `location` text COMMENT 'Location',
  `country_id` text COMMENT 'Country Id'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='amasty_audit_active';

-- --------------------------------------------------------

--
-- 資料表結構 `amasty_audit_log`
--

CREATE TABLE `amasty_audit_log` (
  `id` int(10) UNSIGNED NOT NULL COMMENT 'Id',
  `date_time` datetime DEFAULT NULL COMMENT 'Date Time',
  `username` text COMMENT 'Username',
  `type` text COMMENT 'Type',
  `category` text COMMENT 'Category',
  `category_name` text COMMENT 'Category Name',
  `parametr_name` text COMMENT 'Parametr Name',
  `element_id` int(10) UNSIGNED NOT NULL COMMENT 'Element Id',
  `item` text COMMENT 'Item',
  `store_id` int(11) DEFAULT NULL COMMENT 'Store Id'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='amasty_audit_log';

-- --------------------------------------------------------

--
-- 資料表結構 `amasty_audit_login_attempts`
--

CREATE TABLE `amasty_audit_login_attempts` (
  `id` int(10) UNSIGNED NOT NULL COMMENT 'Id',
  `date_time` datetime DEFAULT NULL COMMENT 'Date Time',
  `username` text COMMENT 'Username',
  `name` text COMMENT 'Name',
  `ip` text COMMENT 'IP',
  `status` text COMMENT 'Status',
  `location` text COMMENT 'Location',
  `country_id` text COMMENT 'Country Id',
  `user_agent` text COMMENT 'User Agent'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='amasty_audit_login_attempts';

-- --------------------------------------------------------

--
-- 資料表結構 `amasty_audit_log_details`
--

CREATE TABLE `amasty_audit_log_details` (
  `id` int(10) UNSIGNED NOT NULL COMMENT 'Id',
  `log_id` int(10) UNSIGNED NOT NULL COMMENT 'Log Id',
  `name` text COMMENT 'Name',
  `old_value` text COMMENT 'Old Value',
  `new_value` text COMMENT 'New Value',
  `model` text COMMENT 'Model'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='amasty_audit_log_details';

-- --------------------------------------------------------

--
-- 資料表結構 `amasty_audit_visit`
--

CREATE TABLE `amasty_audit_visit` (
  `id` int(10) UNSIGNED NOT NULL COMMENT 'Id',
  `username` text COMMENT 'Username',
  `name` text COMMENT 'Name',
  `session_start` datetime DEFAULT NULL COMMENT 'Session Start',
  `session_end` datetime DEFAULT NULL COMMENT 'Session End',
  `ip` text COMMENT 'IP',
  `location` text COMMENT 'Location',
  `session_id` text COMMENT 'Session Id'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='amasty_audit_visit';

-- --------------------------------------------------------

--
-- 資料表結構 `amasty_audit_visit_details`
--

CREATE TABLE `amasty_audit_visit_details` (
  `id` int(10) UNSIGNED NOT NULL COMMENT 'Id',
  `page_name` text COMMENT 'Page Name',
  `page_url` text COMMENT 'Page URL',
  `stay_duration` int(11) DEFAULT NULL COMMENT 'Stay Duration',
  `session_id` text COMMENT 'Session Id',
  `visit_id` int(10) UNSIGNED NOT NULL COMMENT 'Visit ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='amasty_audit_visit_details';

--
-- 已傾印資料表的索引
--

--
-- 資料表索引 `amasty_audit_active`
--
ALTER TABLE `amasty_audit_active`
  ADD PRIMARY KEY (`id`);

--
-- 資料表索引 `amasty_audit_log`
--
ALTER TABLE `amasty_audit_log`
  ADD PRIMARY KEY (`id`);

--
-- 資料表索引 `amasty_audit_login_attempts`
--
ALTER TABLE `amasty_audit_login_attempts`
  ADD PRIMARY KEY (`id`);

--
-- 資料表索引 `amasty_audit_log_details`
--
ALTER TABLE `amasty_audit_log_details`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_amasty_amaudit_details_log_id` (`log_id`);

--
-- 資料表索引 `amasty_audit_visit`
--
ALTER TABLE `amasty_audit_visit`
  ADD PRIMARY KEY (`id`);

--
-- 資料表索引 `amasty_audit_visit_details`
--
ALTER TABLE `amasty_audit_visit_details`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_amasty_amaudit_visit_id` (`visit_id`);

--
-- 在傾印的資料表使用自動遞增(AUTO_INCREMENT)
--

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `amasty_audit_active`
--
ALTER TABLE `amasty_audit_active`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id';

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `amasty_audit_log`
--
ALTER TABLE `amasty_audit_log`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id';

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `amasty_audit_login_attempts`
--
ALTER TABLE `amasty_audit_login_attempts`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id';

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `amasty_audit_log_details`
--
ALTER TABLE `amasty_audit_log_details`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id';

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `amasty_audit_visit`
--
ALTER TABLE `amasty_audit_visit`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id';

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `amasty_audit_visit_details`
--
ALTER TABLE `amasty_audit_visit_details`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Id';

--
-- 已傾印資料表的限制式
--

--
-- 資料表的限制式 `amasty_audit_log_details`
--
ALTER TABLE `amasty_audit_log_details`
  ADD CONSTRAINT `AMASTY_AUDIT_LOG_DETAILS_LOG_ID_AMASTY_AUDIT_LOG_ID` FOREIGN KEY (`log_id`) REFERENCES `amasty_audit_log` (`id`) ON DELETE CASCADE;

--
-- 資料表的限制式 `amasty_audit_visit_details`
--
ALTER TABLE `amasty_audit_visit_details`
  ADD CONSTRAINT `AMASTY_AUDIT_VISIT_DETAILS_VISIT_ID_AMASTY_AUDIT_VISIT_ID` FOREIGN KEY (`visit_id`) REFERENCES `amasty_audit_visit` (`id`) ON DELETE CASCADE;
COMMIT;


` ` ` 

Step4, magento upgrade process...
