### ISSUE TITLE
「Cookie 同意書」 

### ISSUE THREAD

**Issue by uflins** [MRLIVING/magento#22]
網站需要有接受COOKIE 的設計，參考資料，
https://trello-attachments.s3.amazonaws.com/5afd6277f328f85b84ad3941/60c179d871693f25be6d5686/62b1263c2d5b9a6079f64c15da31134a/image.png

**Comment by Peipeixuan** [comment]
![image](https://user-images.githubusercontent.com/43645533/125031840-b8e01280-e0bf-11eb-9c4f-f0e845db9dfc.png)

Open **Cookie Restriction Mode** In configuration
![image](https://docs.magento.com/user-guide/images/images/config-general-web-default-cookie-settings.png)
