### ISSUE TITLE
[layout] repetitive content in the mobile login page

### ISSUE THREAD

**Issue by Eric0329** [MRLIVING/magento#25]
We need to fix the mobile login page layout.
![image](https://user-images.githubusercontent.com/3777869/124859048-bb6c3a80-dfe1-11eb-984f-51d8d6abf31d.png)

**Comment by Peipeixuan** [comment]
fixed it by adding css in magezon header builder - test1
![image](https://user-images.githubusercontent.com/43645533/124890238-6bee3480-e00a-11eb-85eb-9b0e4429f4c7.png)

![image](https://user-images.githubusercontent.com/43645533/124890852-08183b80-e00b-11eb-99b0-64ddf117759f.png)

**Comment by Peipeixuan** [comment]
有測試過是因為 header page builder 造成他出現多個，但檢查 PHP 和 phtml 之後還是找不太到出現這些的原因（感覺是處理的時候沒有刪掉原生的），所以就用CSS 把它隱藏。

**Comment by Eric0329** [comment]
resolved
