### ISSUE TITLE
[layout] popup content be covered by header

### ISSUE THREAD

**Issue by Peipeixuan** [MRLIVING/magento#26]
![image](https://user-images.githubusercontent.com/43645533/125057041-6876ae00-e0db-11eb-8989-36683cf0ada5.png)

**Comment by Peipeixuan** [comment]
![image](https://user-images.githubusercontent.com/43645533/125057650-0ec2b380-e0dc-11eb-8ccc-9c483fd0fee7.png)

Override path: `/var/www/html/magento2/app/design/frontend/Mrl/mrl_luma/web/css/source/components/_modals.less`
Overrided : `/var/www/html/magento2/vendor/magento/magento2-base/lib/web/css/source/components/_modals.less`

![image](https://user-images.githubusercontent.com/43645533/125061634-1d12ce80-e0e0-11eb-8c36-9ed1e641af91.png)

**Comment by Peipeixuan** [comment]
發現上面這樣改會讓登入視窗掉下去
![image](https://user-images.githubusercontent.com/43645533/125252723-44111080-e32b-11eb-9666-46ff3fa893b0.png)

所以改成這樣，一律讓他在中間
![image](https://user-images.githubusercontent.com/43645533/125255769-5b9dc880-e32e-11eb-8b46-61ae94957097.png)

**Comment by Eric0329** [comment]
resolved.
