### ISSUE TITLE
[backend console] 新增交期comment

### ISSUE THREAD

**Issue by Peipeixuan** [MRLIVING/magento#49]
在 **內部溝通** 、 **order comment** 新增第一批交期、第二批交期等資訊

**Comment by Peipeixuan** [comment]
Use **Update Attributes** button
![image](https://user-images.githubusercontent.com/43645533/140025048-e5d70675-8643-4e56-b895-1460bf40b4de.png)

**Comment by Eric0329** [comment]
resolved.
