### ISSUE TITLE
Google Tag Manager Preview not connect

### ISSUE THREAD

**Issue by Peipeixuan** [MRLIVING/magento#63]
![image](https://user-images.githubusercontent.com/43645533/146490489-6496fb05-21a3-44f1-b476-2c5fcc8c43c7.png)

**Comment by Peipeixuan** [comment]
Because of Content Security Policy.
![image](https://user-images.githubusercontent.com/43645533/146490537-314f7258-dedf-400a-9ee1-a79fd5cf14e4.png)

Need to disable Magento_Csp module.
[Reference](https://meetanshi.com/blog/disable-magento-2-content-security-policy/)

**Comment by Eric0329** [comment]
Well done.
